### ISSUE TITLE
Recipe for Firebase authentication

### ISSUE THREAD

**Issue by kuceb** [cypress-io/cypress-example-recipes#118]

**Comment by iancrowther** [comment]
```
import firebase from 'firebase'

firebase.initializeApp({
  apiKey: '',
  authDomain: '',
  databaseURL: '',
  projectId: '',
  storageBucket: '',
  messagingSenderId: ''
})

describe('Home', () => {
  beforeEach(function () {
    cy.exec('firebase database:set / cypress/fixtures/seed.json --confirm')
    firebase.auth().signInWithEmailAndPassword('[username]', '[password]')
  })

  it('logs in programmatically without using the UI', function () {
    cy.visit('/')
    cy.get('#username').contains(firebase.auth().currentUser.email)
  })
})
```

**Comment by fikrikarim** [comment]
Hi I'm trying to understand the solution here. Can you please explain the solution, and whether it is the best practice to mock firebase auth? I'm learning the best way to mock the firebase auth. Thanks!

**Comment by romines** [comment]
@iancrowther I don't understand how you can call `firebase.initializeApp({ ... })` if it is already called in app bootstrapping.

**Comment by bahmutov** [comment]
I have looked at Firebase auth here: https://github.com/bahmutov/cypress-firebase-auth-example and it is pretty straightforward to log in using UI or `firebase.auth().signInWithEmailAndPassword` and I probably will a little bit more into this.

**Comment by bahmutov** [comment]
Related: 
- https://github.com/prescottprue/cypress-firebase
- https://github.com/bahmutov/cypress-firebase-auth-example

**Comment by logicalicy** [comment]
> I don't understand how you can call firebase.initializeApp({ ... }) if it is already called in app bootstrapping.

Cypress is not aware of the initialised instance of Firebase when the integration test is run. But the app's initialised Firebase instance could be imported/re-used perhaps? `import firebase from '../../src/lib/firebase';` or similar

**Comment by mesqueeb** [comment]
I also wanna know how to use the browser's firebase instance, as opposed to creating a new firebase instance.

any advice?
