### ISSUE TITLE
Show recipe for interacting with common bootstrap elements

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-example-recipes#13]
Such as dropdown, dialogs, etc.

Also create a custom child command for programmatically interacting with JS api's directly to avoid using the DOM.

**Comment by livthomas** [comment]
How can we wait for `shown.bs.modal` event? I try to click on a submit button with `data-dismiss="modal"` attribute as soon as the modal is shown. Sometimes it closes the modal, sometimes it doesn't. But my custom onclick handler is always executed. It seems like Cypress clicks on the button before Bootstrap close hook is binded.
