### ISSUE TITLE
Awaiting a vuex action in a Cypress command (or beforeEach hook)

### ISSUE THREAD

**Issue by dannyrb** [cypress-io/cypress-example-recipes#133]
I'm creating this issue in response to this [Disqus thread](https://disqus.com/home/discussion/cypress-io/testing_vue_web_applications_with_vuex_data_store_rest_backend/#comment-3839185477) and the [Testing Vue Web Applications With Vuex Data Store](https://www.cypress.io/blog/2017/11/28/testing-vue-web-application-with-vuex-data-store-and-rest-backend/index.html) blog post.

I'm using an existing `login` vuex action in a Cypress `beforeEach` hook to log a user in before each test. The `login` vuex action is asynchronous, so the `beforeEach` hook ends and aborts in-progress calls before it completes.

I can get my action to wait for completion by doing something like this:

```
Cypress.Commands.add('logIn', ({ username, password } = {}) => {
    getStore().then((store) => {
        const params = `username=${username}&password=${password}`
        store.dispatch('logIn', params)
        getStore().its('getters.isAuthenticated').should('eq', true)
    })
})
```

But this has the downside of:
- Asserting in my `beforeEach` (feels weird)
- If my `login` action does other work (additional XHR calls), they are aborted when my condition is true.

It would be nice if I could `await` my vuex action before my test start. When I attempt to `await`, I get the following error:

> regeneratorRuntime is not defined

My project was scaffolded with Vue CLI 3, but my Googling shows that it may simply not be possible to use `async`/`await` within Cypress? If that's not the case, I'm not sure how best to configure my project to add this functionality.

**Comment by bahmutov** [comment]
what's the smallest example I can use to recreate this? A Vuex store async action used from `beforeEach` spec hook?

**Comment by amirrustam** [comment]
I did a scrappy reproduction here: https://github.com/amirrustam/recipes-133
I also used the Vue CLI v3. 

Here is how I setup the Vuex store:

```js
  state: {
    auth: true
  },
  mutations: {
    setAuthentication (state, value = false) {
      state.auth = value
    }
  },
  actions: {
    logIn ({ commit }) {
      return new Promise((resolve, reject) => {
        // fake time consuming login request
        setTimeout(() => {
          commit('setAuthentication', false)
          resolve()
        }, 3000)
      })
    }
  },

  getters: {
    isAuthenticated: state => state.auth
  }
```

So just like your code, there is an `isAuthenticated` getter and a `logIn` action. For the `logIn`action I fake the login request with a 3 sec timeout within a promise. On purpose, `isAuthenticated` starts as *true* and the `logIn` action eventually sets it to *false*.

Now here are is the `commands.js`:

```js
Cypress.Commands.add('vuex', () =>
  cy.window()
    .its('app.$store')
)

Cypress.Commands.add('logIn', () =>
  cy.vuex()
    .then(store => store.dispatch('logIn'))
    .then(() => cy.vuex().its('getters.isAuthenticated').should('eq', true))
)
```

Instead of the `getStore`, I'm just doing `cy.vuex()`. It's the same thing, just a different day!
After getting a Cypress wrapped vuex `$store`, chain 2 `thens`. First dispatch the action, then make the assertion on `getters.isAuthenticated`. 

This resulted in Cypress waiting for that 3 second promise to resolve before making the assertion. Also notice that `isAuthenticated` started off as true. Which in your case, all the fancy stuff you're doing within your `logIn` action will resolve prior to the assertion.

I believe I'm observing things correctly to make this claim, so please confirm with my reproduction repo, and we'll take it from there.

**Comment by dannyrb** [comment]
@amirrustam, here I am sitting down to write up an example, and I've come to find that you've already done it. Thank you for your hard work!

The only difference I see is that my `logIn` action is `async`:
```
async logIn({ dispatch }, data) {
    try {
      const response = await api.auth.logIn(data)
      dispatch('setAuthenticationAndInit', response)
    } catch (err) {
      const friendlyError =
        'Unable to sign in. Incorrect password or username. Please try again.'
      throw new Error(err.response ? friendlyError : undefined)
    }
  }
```

Your comments:

> On purpose, isAuthenticated starts as true and the logIn action eventually sets it to false.

> Also notice that isAuthenticated started off as true. Which in your case, all the fancy stuff you're doing within your logIn action will resolve prior to the assertion.

Lead me to believe that we're on the same page. The issue (as I see it) are requiring assertions in the `beforeEach` hook, and that additional in-progress XHR requests are aborted if they have not resolved before the `isAuthenticated` assertion is true.

IE. We load user settings, static dropdown data, etc. Following a successful login.

I hope that makes sense. Please feel free to ask for more information, or provide feedback/criticism. Also, I appreciate your implementation and snippets. We're in the early stages of adding Cypress, and seeing your style/approach is nice.

**Comment by amirrustam** [comment]
In your logIn action you need to await all your dispatch calls. For example, you should also be awaiting `dispatch('setAuthenticationAndInit', response)`.

I've also update my [previous response](https://github.com/cypress-io/cypress-example-recipes/issues/133#issuecomment-379106797) with a much cleaner and better way. Please check it out.

**Comment by bahmutov** [comment]
There is no way for us to get the promise from `cy.vuex().invoke('dispatch', 'logIn')` and wait for it @amirrustam ?

**Comment by brian-mann** [comment]
@bahmutov Cypress will automatically await promises returned by `invoke`

**Comment by bahmutov** [comment]
@brian-mann yeah, we found it, just our docs do not say it for `invoke`, opening an issue for that in documentation.
