### ISSUE TITLE
Add recipe with web sockets

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#138]
Maybe with FeathersJS client?

**Comment by mjhea0** [comment]
thoughts https://github.com/mjhea0/cypress-example-recipes/tree/master/examples/websockets?

**Comment by jennifer-shehane** [comment]
Related: https://github.com/cypress-io/cypress-documentation/issues/558

**Comment by samlucax** [comment]
Any updates?

**Comment by DiogoCercilio** [comment]
@samlucax this link may be helpful:
https://github.com/cypress-io/cypress/issues/2492#issuecomment-652927160

**Comment by mikaelboff** [comment]
any updates?

**Comment by bahmutov** [comment]
Example video mocking socket from the test https://www.youtube.com/watch?v=soNyOqpi_gQ
