### ISSUE TITLE
Travis marks builds as failed but they passed

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#156]
Some builds in internal PRs are marked as failed, but each command internally was successful. Example https://travis-ci.org/cypress-io/cypress-example-recipes/jobs/388102701 

From discussion in https://github.com/travis-ci/travis-ci/issues/8082 seems this might be related to
- using secret variables
- background processes (we use `npm start &`)

**Comment by jennifer-shehane** [comment]
Could this be related to some of our users issues?
- https://github.com/cypress-io/cypress/issues/1453
- https://github.com/cypress-io/cypress/issues/1333

**Comment by bahmutov** [comment]
no, our test run exits successfully, it is Travis doing some dumb thing and not understanding what is going on at its end.
