### ISSUE TITLE
Improve TypeScript with Webpack example

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-example-recipes#165]
So, I was trying to 'copy' the recipe [TypeScript with Webpack](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/preprocessors__typescript-webpack) in order to use it in my own project. I have some suggestions. 

1. Include the required dev packages in the `package.json`. I was looking to include the required packages, but none were listed in the `package.json` or clearly in the README, so I initially installed none - only to run into numerous errors because I was missing deps. What was needed, but not clear:
  - `npm install --save-dev @cypress/webpack-preprocessor`
  - `npm install --save-dev ts-loader`
  - `npm install --save-dev typescript`
2. Update the `build` script to be copy/pastable. Right now it has static `./cypress/integration/spec.ts` coded in, should be `"build": "../../node_modules/.bin/webpack --output-filename out.js --entry ./cypress/integration/*.ts"` at least.

**Comment by awentzel** [comment]
For #2 above may consider this webpack configuration for directory support `--entry ./cypress/integration/**/*.ts`

Also, I was able to add a `"types": ["cypress"]` to my tsconfig.json file and get support for ES6 which i didn't see in recommended approach in the documentation.

**Comment by jennifer-shehane** [comment]
@awentzel Yeah, it actually is mentioned on the docs side, which isn't in sync with this example. https://on.cypress.io/typescript-support#Configure-tsconfig-json

**Comment by sheam** [comment]
IT also isn't clear how to run or use this example. I tried `npm install` in the root of this repo. Then in the TS/WP directory running `npm run cypress:run`, or `npm run lint`, but basically nothing works.

Also, I would think most people will have a folder/project just for testing. Not a project within a project like this setup.

**Comment by clight-fastly** [comment]
I'd love to see this example updated with more than just the webpack plugin enabled. I tried to get https://github.com/TheBrainFamily/cypress-cucumber-preprocessor working in conjunction with the webpack plugin to no avail.

**Comment by Frozenfire92** [comment]
I also experienced many of the issues @jennifer-shehane ran into.

Noting I also needed to install webpack `npm install --save-dev webpack` or the builds would fail when going to run the spec

Noting without the `watch` flag in `webpack.config.js` the "live reload" from cyrpess open won't work. Likely worthwhile adding to this example

```js
module.exports = {
  watch: true,
  ...
}
```

**Comment by larshp** [comment]
also experiencing multiple issues
