### ISSUE TITLE
file-upload-react 

### ISSUE THREAD

**Issue by zeinMch** [cypress-io/cypress-example-recipes#200]
Hi,
I am trying to test the file upload using cypress, but it doesn't work :( 

<img width="911" alt="screen shot 2018-08-24 at 9 07 42 am" src="https://user-images.githubusercontent.com/39551878/44573334-44fdc600-a77e-11e8-854f-12412a921556.png">
<img width="1115" alt="screen shot 2018-08-24 at 9 06 15 am" src="https://user-images.githubusercontent.com/39551878/44573335-45965c80-a77e-11e8-9fdc-ded610a3a379.png">
<img width="942" alt="screen shot 2018-08-24 at 1 07 34 pm" src="https://user-images.githubusercontent.com/39551878/44583810-c7967d80-a79e-11e8-80f9-3e7ce03878d3.png">

**Comment by henryson** [comment]
I have the same problem. The trigger API does not mention an option to pass a file object. And triggering the event indeed results in an empty fileList. Should this work?

**Comment by jennifer-shehane** [comment]
There are quite a few workarounds people have added to this issue: https://github.com/cypress-io/cypress/issues/170

**Comment by abramenal** [comment]
https://github.com/abramenal/cypress-file-upload

It also contains some usage examples (for plain HTML input, react-dropzone component).
