### ISSUE TITLE
Testing css pseudo-element

### ISSUE THREAD

**Issue by shadrech** [cypress-io/cypress-example-recipes#207]
Is there a way to test css pseudo elements? For example to check the text in the `content` attribute?

**Comment by jennifer-shehane** [comment]
You should be able to make assertions on css styles like so:

```
cy.get('.header')
    .should('have.css', 'content')
    .and('include', 'beta!')
```

This repo is only for issues relating to Cypress example recipes. In the future, if you want to open an issue on our main project, you can open it [here](https://github.com/cypress-io/cypress/issues/new). 

Also, check out our [community chat](https://gitter.im/cypress-io/cypress), it can be helpful for debugging issues or just answering questions you have about Cypress.
