### ISSUE TITLE
How to preprocess *spec.ts with @babel/preset-typescript

### ISSUE THREAD

**Issue by matt-erhart** [cypress-io/cypress-example-recipes#220]
After looking at examples and the browserify or webpack preprocessor docs, I could not get typescript syntax to work in a spec file without error. I tried way too many combos of config files and plugins. I think something like the following should work but it throws errors from ts syntax in a spec file: 

```js
const browserify = require("@cypress/browserify-preprocessor");
const presetTs = require.resolve("@babel/preset-typescript")
module.exports = on => {
  const options = browserify.defaultOptions
  options.browserifyOptions.transform[1][1].presets.push(presetTs)
  on("file:preprocessor", browserify(options));
};
```

What am I doing wrong here? Would be great to get some updated typescript examples as it's pretty rough to get going with ts specs now.

**Comment by bahmutov** [comment]
sure @matt-erhart can you specify exactly what the setup for your repo is? Versions of babel and plugins? The best would be for you to make a pull request to this repo after installing dependencies in the root (in this repo all dependencies are in the root) and making new examples subfolder with just your case. Even if it errors we can fix it and do the example that would work for you (and other people in your situation)

**Comment by matt-erhart** [comment]
https://github.com/matt-erhart/CodeExperiments

Working toward fast animation/interaction testing in that repo.  Had to update cypress-app-watcher-preprocessor to get source changes to rerun tests, which I posted here: https://github.com/TheBrainFamily/cypress-app-watcher-preprocessor/issues/2

**Comment by bahmutov** [comment]
I still don't see what you 
- do step by step
- expect to see at each step
- what Cypress does at each step

Without easily reproducible step by step report, I am not sure I should spend any time investigating this issue, since there are a lot of other things I could spend time on.

**Comment by matt-erhart** [comment]
Goal is in the title, implementation details don't matter, and I'm just checking out cypress, so I'll not be spending time on it either. Maybe I'll try test cafe instead.
