### ISSUE TITLE
Add example for dynamically generating tests

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#233]
- "simple" generation where we have a single test for each item from the list
- loading fixture and generating a test per item
- requesting data from the server to generate tests?

**Comment by jennifer-shehane** [comment]
Examples in the docs of dynamically generated tests: 

- https://on.cypress.io/viewport#Examples
- https://on.cypress.io/using-cypress-faq#Can-I-run-the-same-tests-on-multiple-subdomains
