### ISSUE TITLE
application-code example doesn't run

### ISSUE THREAD

**Issue by Terrycoco** [cypress-io/cypress-example-recipes#257]
when I run 
`npm run cypress:open`
on the unit-testing__application-code example I get the following error:

`sh: 1: ../../node_modules/.bin/cypress: not found`

Note, there is no "start" command in package.json at all.  I have run npm install on the entire project at the root.

**Comment by Terrycoco** [comment]
setting up examples folder from git clone.  When I try to run the unit-testing__application-code example I get this:

sh: 1: ../../node_modules/.bin/cypress: not found

There is not a "start" in package.json

**Comment by bahmutov** [comment]
Omg I’m just writing a readme for this example in another pull request to explain this :) since this is application code, no need to run server start to run the tests. Just run cypress:open

**Comment by bahmutov** [comment]
@Terrycoco have you done `npm install` from the root repo? This will install Cypress - all example folders just load Cypress from the root to avoid installing bunch of copies of the same package
