### ISSUE TITLE
Upgrade Cypress to 3.2.0

### ISSUE THREAD

**Issue by clarmso** [cypress-io/cypress-example-recipes#258]
The renovate bot has not detected the new version of Cypress (3.2.0).  The package.json is still pointing to the version 3.1.5.

I am tempted to submit a PR to upgrade Cypress, but am afraid that the proper way to fix the issue is to use the Renovate Bot.  renovate.json has included Cypress.  Renovate Bot is supposed to check for update every day between 2am and 4am, but something is preventing it from checking for Cypress updates everyday.

**Comment by jennifer-shehane** [comment]
Feel free to open a PR for this!
