### ISSUE TITLE
Do we need the recipe details in the readme?

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#267]
Currently when you click on the recipe name, like "Adding Chai Assertions"

<img width="896" alt="Screen Shot 2019-03-27 at 9 16 09 AM" src="https://user-images.githubusercontent.com/2212006/55078721-268fde00-5071-11e9-9c7d-9b0e0a7183b1.png">

you jump to another place in the same README file with more details about the recipe. You have to guess that the title of the recipe actually leads to the example folder

<img width="646" alt="Screen Shot 2019-03-27 at 9 16 22 AM" src="https://user-images.githubusercontent.com/2212006/55078796-49ba8d80-5071-11e9-9f56-f8cc98bf83ac.png">

The README in the recipe example folder actually has a lot more details about this particular recipe

<img width="982" alt="Screen Shot 2019-03-27 at 9 16 34 AM" src="https://user-images.githubusercontent.com/2212006/55078822-59d26d00-5071-11e9-80ae-92c86d7ac4c3.png">

## Proposal

Remove recipes descriptions from the root README file, instead jump directly from the recipe table links to the example folder. Eliminates duplication, and each example folder now has a README file

**Comment by bahmutov** [comment]
Related: we probably need to do something about the https://on.cypress.io/recipes page too. Right now it is manually updated in both places, but can probably be auto-generated

**Comment by matheuseabra** [comment]
@bahmutov Good catch, I'll take a look at it
