### ISSUE TITLE
Add links to other repos

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#294]
It would be nice to have a section linking to other repos - the ones that show visual testing, code coverage, etc.

**Comment by matheuseabra** [comment]
Nice, yes I'll try to gather the links and submit a small PR with this content upgade. Thanks for suggesting this @bahmutov

**Comment by matheuseabra** [comment]
Mark as closed: https://github.com/cypress-io/cypress-example-recipes/pull/295
