### ISSUE TITLE
Data driven test

### ISSUE THREAD

**Issue by waitsangbv** [cypress-io/cypress-example-recipes#310]
I tried to create multiple tests using forEach on a dynamic array retrieved from dB. I use cy.task to get data from dB fine. Problem is that alldata.forEach(((item)...) is always executed before the before('data'...) codes. See codes below. Hence error happens as alldata is not defined before before('data'...) is executed. I tried many different approaches but failed to find a way to execute some nodejs first, and feed the results to it(...)
++++++++++++++++++++++++++
describe('analyse test', function() {
	before('data', function() {
		cy.task('get_Data')
		.then((data) => {
			alldata = data			
		})
	})
	alldata.forEach((item) => {
		it('test ' + count, function () {
			cy.log("ReportName: " + item.ReportName)
			cy.log("ReportType: " + item.ReportType)
		})
		count++;
	})
})

**Comment by bahmutov** [comment]
See how I am fetching some data from the server and then generate dynamic set of tests inside a new `describe` block in https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__dynamic-tests in spec file https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/fundamentals__dynamic-tests/cypress/integration/dynamic-spec.js
