### ISSUE TITLE
Add example for stubbing typing text into window.prompt and confirming correct alert response

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-example-recipes#339]
There is a full example here: https://github.com/cypress-io/cypress/issues/5316#issuecomment-541173970

Should be added to this example folder https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__window

**Comment by hazim** [comment]
Hi @jennifer-shehane 
How can one do that? am I meant to copy the content and paste it in as a new markdown file? 
Would love to learn how this is done or if you could refer me to some place to read up on it. 

Many thanks.

**Comment by jennifer-shehane** [comment]
The example is linked in the comment above. Will paste the content here:

Example `index.html` of my test application, but essentially when a button is clicked, a window prompt appears.

```html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Stubbing Window Prompt</title>
</head>
<body>
    <ul>
        <li>
            <h1>My Application</h1>
            <button id="prompt">Prompt</button>
        </li>
    </ul>

    <script>
        var btn = document.getElementById('prompt')
        btn.addEventListener('click', function (event) {
            let sign = prompt("What's your sign?");

            if (sign === "scorpio") {
                alert("Wow! I'm a Scorpio too!");
            }
        })
    </script>
</body>
</html>
```

My Cypress test file. 

1. We are stubbing the text that is entered into the prompt, this will be 'faking' as if a real user typed this. 
2. We are spying on the 'alert' - which is the 'success' message that displays after the text is entered. Then we are asserting that the correct message is displayed - which would test whether they wrote 'scorpio' in my case.

```js
it('window prompt test', function () {
  cy.visit('/index.html', {
    onBeforeLoad(win) {
      cy.stub(win, 'prompt').returns('scorpio')
      cy.stub(win, 'alert').as('windowAlert')
    }
  })
  
  cy.get('#prompt').click().then(function () {
    expect(this.windowAlert).to.be.calledWith('Wow! I\'m a Scorpio too!')
  })
})
```

This is the result in the Cypress Test Runner after, notice that you can click within the Command Log to see more details about Spies/Stubs.

<img width="1072" alt="Screen Shot 2019-10-11 at 2 24 45 PM" src="https://user-images.githubusercontent.com/1271364/66675231-e837c600-ec32-11e9-9eae-41d7c8105789.png">

You will no longer see the 'prompt' window pop up and stop execution of the tests since we're handling the type and confirm in Cypress tests.

**Comment by hazim** [comment]
Thanks @jennifer-shehane for getting back on this!
 
Could I have a try at it?

**Comment by jennifer-shehane** [comment]
@hazim Sure!

**Comment by arvinderloyalty** [comment]
Hey @jennifer-shehane thanks for providing the work around. However, in my application when I set password and click on confirm button, the different URL opens in the same tab which ask for QA environment credentials in the alert window. The above code is working for that flow. Could you please suggest something else?
