### ISSUE TITLE
Can i spy fetch reguest 

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress-example-recipes#344]
I couldn't find what i was looking for. I have fetch api request and i want to control the request header and request body. Are there any example for that and is this possible with cypress ?

**Comment by gabbersepp** [comment]
have you looked into this: https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/stubbing-spying__window-fetch/ and played a bit around with this example?

**Comment by bahmutov** [comment]
yes, that recipe shows how to spy / stub `window.fetch` or stub network requests.
