### ISSUE TITLE
Remove unnecessary files from examples

### ISSUE THREAD

**Issue by gabbersepp** [cypress-io/cypress-example-recipes#348]
In my recently added example (spy on console.log) I used the example from "spy on window". During the review process some files were removed: https://github.com/cypress-io/cypress-example-recipes/pull/346/commits/c8fe6e6612788d9ce38b4c8c69bae56edc28e87a

Those Unnecessary files should be removed from all examples to make it easier for new contributors.

**Comment by jennifer-shehane** [comment]
Yeah, I agree

**Comment by gabbersepp** [comment]
sorry, did not know that the commits do not disappear after resetting my branch. had to do the same stuff a few times. The next time I will make sure that this does not happen again. The latest commit can be seen here: https://github.com/cypress-io/cypress-example-recipes/pull/358
