### ISSUE TITLE
Warn about untested recipes without `test:ci` from test-examples.js

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#361]
When test-examples.js finds all recipes with `npm run test:ci` command or `npm run test:ci:chrome` it should print recipes WITHOUT it to warn users about new recipes that are not tested

**Comment by gabbersepp** [comment]
Something like this:

```js
const hasPackageScriptName = (folder) => {
  const filename = resolve(join(folder, 'package.json'))

  if (!fs.existsSync(filename)) {
    return false
  }

  const { scripts } = require(filename)

  if (!scripts || !scripts[scriptName]) {
    const example = filename.match(/.*?([^\/\\]+)[\\\/]package\.json/i)[1];
    console.warn('example %s does not have script "%s"', example, scriptName)
    return
  }

  return scripts && scripts[scriptName]
}
```
This will print:
![image](https://user-images.githubusercontent.com/3234900/67717247-a1392700-f9cd-11e9-92cf-71c45426a42a.png)

I am not sure if this is  enough?
