### ISSUE TITLE
Example for testing a Chrome browser extension

### ISSUE THREAD

**Issue by kylemh** [cypress-io/cypress-example-recipes#385]

**Comment by jennifer-shehane** [comment]
I think this is a great idea 👍

**Comment by kylemh** [comment]
I'll be resolving this issue myself with a PR within the next month or so if nobody else snags it!

**Comment by bahmutov** [comment]
Note that Vue DevTools Chrome extension is using Cypress to test itself https://github.com/vuejs/vue-devtools

**Comment by kylemh** [comment]
Stellar. I'll take from this and add to recipes + documentation via PRs at some point!
