### ISSUE TITLE
cannot start server in example directory

### ISSUE THREAD

**Issue by ninadkambli** [cypress-io/cypress-example-recipes#404]
I am trying to start a server inside "blogs__application-actions" directory, but am getting below error
```
D:\CypressExamples\cypress-example-recipes>npm install
npm WARN @cypress/eslint-plugin-dev@5.0.0 requires a peer of babel-eslint@^7.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN @cypress/eslint-plugin-dev@5.0.0 requires a peer of eslint-plugin-mocha@^4.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN chai-enzyme@1.0.0-beta.1 requires a peer of chai@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.0 requires a peer of webpack@^4.36.0 but none is installed. You must install peer dependencies yourself.   
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\react-scripts\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 940210 packages in 58.389s
found 8 vulnerabilities (1 low, 2 moderate, 4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

D:\CypressExamples\cypress-example-recipes>cd D:\CypressExamples\cypress-example-recipes\examples\blogs__application-actions        

D:\CypressExamples\cypress-example-recipes\examples\blogs__application-actions>npm run start --if-present

> blogs__page-actions@1.0.0 start D:\CypressExamples\cypress-example-recipes\examples\blogs__application-actions
> ../../node_modules/.bin/http-server -p 8888 --silent -c-1

'..' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blogs__page-actions@1.0.0 start: `../../node_modules/.bin/http-server -p 8888 --silent -c-1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the blogs__page-actions@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ninad\AppData\Roaming\npm-cache\_logs\2020-01-20T18_21_06_803Z-debug.log

D:\CypressExamples\cypress-example-recipes\examples\blogs__application-actions>
```

Please help I am not able to make progress due to such issues.
I already executed npm install in root directory and all node modules are downloaded in node_modules folder

**Comment by jennifer-shehane** [comment]
I'm not getting the same error, but when trying to run `npm start` from the example you're trying to run, the server doesn't ever seem to start for me. My output:

<img width="933" alt="Screen Shot 2020-01-21 at 11 17 16 AM" src="https://user-images.githubusercontent.com/1271364/72776229-d4432d80-3c3f-11ea-971c-a3c6d231e0b8.png">

Did you look at the logs at C:\Users\Ninad\AppData\Roaming\npm-cache\_logs\2020-01-20T18_21_06_803Z-debug.log ?

What operating system are you running this on?

**Comment by ninadkambli** [comment]
you are right server doesn't start using npm run
I used "npx http-server -p 8888 --silent -c-1" command instead and its working file.
Changes should be made in package.json file in order to start server

**Comment by bahmutov** [comment]
1. Warnings during `npm install` are normal, ignore them
2. `'..' is not recognized as an internal or external command` is because you are using `npm start` command that uses Linux paths to launch Cypress. Cypress is up two folders in the root folder, thus the path starts with `../../...` and Windows crashes and burns.

If you want to start, there is `npm run start:win` script in that `package.json` file, BUT you need to install globally [bin-up](https://github.com/bahmutov/bin-up) utility first.

```
npm i -g bin-up
cd examples/blogs__application-actions
npm run start:win
```

3. when you start the server, it is very quiet due to `--silent` flag. So the best way to check if the server is truly up and running is by opening `localhost:8888` in your browser to see the website.

**Comment by ninadkambli** [comment]
Thanks @bahmutov for this in detailed explanation.  Now everything works fine on windows
