### ISSUE TITLE
iFrame stubbing not working

### ISSUE THREAD

**Issue by dudewad** [cypress-io/cypress-example-recipes#425]
Using Cypress 3.8.2 with Chrome.

The examples provided here are not working for me:
https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/blogs__iframes/cypress/integration

Specifically referring to the `xhr-spec.js` example.

In particular, this snippet:
```js
const getIframeWindow = () => {
  return cy
  .get('iframe[data-cy="the-frame"]')
  .its('0.contentWindow').should('exist')
}

const replaceIFrameFetchWithXhr = () => {
  // see recipe "Stubbing window.fetch" in
  // https://github.com/cypress-io/cypress-example-recipes
  getIframeWindow().then((iframeWindow) => {
    delete iframeWindow.fetch
    // since the application code does not ship with a polyfill
    // load a polyfilled "fetch" from the test
    iframeWindow.eval(polyfill)
    iframeWindow.fetch = iframeWindow.unfetch

    // BUT to be able to spy on XHR or stub XHR requests
    // from the iframe we need to copy OUR window.XMLHttpRequest into the iframe
    cy.window().then((appWindow) => {
      iframeWindow.XMLHttpRequest = appWindow.XMLHttpRequest
    })
  })
}
```
...does not work for me at all. `cy.get('iframe').its('0.contentWindow')` throws an error:
`TS2345: Argument of type '"0.contentWindow"' is not assignable to parameter of type 'number'.`
I get this error in intellisense as well as at runtime.

I noticed that in 3.7.x you released an upgrade to allow `its` to accept a number. It seems that this is the only override that is being used. Exactly zero of our `get()` calls can be chained with `its()` calls where `its()` uses a property string. I've tried a number of different formats, none seem to work.

I've been able to access the iframe and test against its contents by doing:
```js
cy.get('iframe').then(iFrame => {
    cy.wrap(iFrame.contents().find('body'))
      .find('launcher-bar');
  });
```
However, within this handler I'm unable to implement any form of the XMLHttpRequest switching (i.e. the `iframeWindow.XMLHttpRequest = appWindow.XMLHttpRequest` trick doesn't work). Calls always fail because they try to go to localhost and don't get caught by stubbing.

Am I missing something in configuration or usage? I've read the docs for `its()` and am 100% certain I'm following them to the letter, and the example given I started clean with and copy/pasted and it still won't work.

Any info could be helpful. Thanks

**Comment by bahmutov** [comment]
Is this recipe NOT working or is it failing a TypeScript check? I believe from your comments that it is failing a TS check. Add this

```
// @ts-ignore
.its('0.contentWindow')
```

Basically what happens is that TS for `.its` understands a single property from the subject, but not when you do compound props like `0.contentWindow`. You could split it into `.its(0).its('contentWindow')` but I don't like it that much - because you are splitting commands, limiting the retry-ability https://on.cypress.io/retry-ability#Merging-queries

For now, I have opened an issue about it https://github.com/cypress-io/cypress/issues/6431

**Comment by dudewad** [comment]
I tried that yesterday. It fails regardless. The "runtime" error that shows in Cypress is a wall of red text (am not reproing it now because I've moved on but can grab a screenshot if you don't know what I'm referring to).
Thanks for being so responsive, means a lot to the community, as you know.

**Comment by dudewad** [comment]
FWIW, I looked at the d.ts and it looks like the interfaces are "correct", yet it seems to be ignoring the original overload that allows for strings.

**Comment by bahmutov** [comment]
Hmm I don’t know how we could confirm or debug this, since it passes on multiple tests in this repo

**Comment by dudewad** [comment]
You're right. It is probably a problem on my end. If I figure it out I'll let you know. Thank you for your time anyways.
