### ISSUE TITLE
How to get data excel using cypress?

### ISSUE THREAD

**Issue by vSixty** [cypress-io/cypress-example-recipes#431]
How to get data excel using cypress? Please give solution.

**Comment by CypressJoseph** [comment]
Assuming you are trying to do property-driven testing, please look here for more details about how to do [Dynamic Test cases](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__dynamic-tests). If you are trying to derive test cases from data files, there are plenty of tools in the ecosystem to handle the data-file-to-JSON side of it -- maybe consider [`csv-parser`](https://www.npmjs.com/package/csv-parser) for ingesting tabular data. If you could tell us more about your use case we may be able to provide more narrow guidance.

**Comment by jennifer-shehane** [comment]
There's an example of getting and using csv data here in this repo also. https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__csv-table
