### ISSUE TITLE
Not able to select new tab opened and continue testing

### ISSUE THREAD

**Issue by dennismail4u** [cypress-io/cypress-example-recipes#479]
I have a scenario where on a page, it opens a new tab on clicking a span element and wanted to continue testing on that new window. The url on the new window is an encrypted dynamic one. Can you help me how to achieve this.

Scenario:
- Login link like a span element on a page
- On click, it opens a new tab and need to continue login from there..but cannot directly access that url.

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to Cypress example recipes. If you want to open an issue on our main project, you can open it [here](https://github.com/cypress-io/cypress/issues/new), completely filling out the provided issue template. This issue will be closed in this repository.

Also, check out our [community chat](https://gitter.im/cypress-io/cypress), it can be helpful for debugging issues or just answering questions you have about Cypress.
