### ISSUE TITLE
Unable to do a "npm install" because of cy-spok

### ISSUE THREAD

**Issue by gabbersepp** [cypress-io/cypress-example-recipes#482]
Hi,
i checked out the current master and run "npm install" but got an error:

"Could not install from "node_modules\cy-spok\spok@github:bahmutov\spok#7a1c65c9573ce4849bb0ee2bfdc93868171eb3f4" as it does not contain a package.json file."

**Comment by gabbersepp** [comment]
deleting the cy-spok section in packages-lock leads to a successful npm install

**Comment by jennifer-shehane** [comment]
Yeah, I had pm'd @bahmutov about this before. Not sure what's up with his dep.
