### ISSUE TITLE
Opening multiple tab at same time using cypress.

### ISSUE THREAD

**Issue by Pushpanjali1993** [cypress-io/cypress-example-recipes#489]
I am aware that current version of Cypress does not support this functionality, and i have run through the given workaround recipes (Spying-on-window , tab-handling-links etc) but could not get it running :(

Problem statement : 
1) I need to open the parent window say google.com for example
2)At the same time need to open child window say github.com for example
3)Navigate back to parent window , click on some button.
4)Come back to child window to perform some actions after clicking on that button on parent window.
5)Navigate back to parent window.
6)And i need to navigate between these two windows back and forth.

something similar like https://www.toolsqa.com/selenium-webdriver/switch-commands/

Help is much appreciated.

Thanks.

**Comment by jennifer-shehane** [comment]
This is not currently possible as we do not support opening separate windows in Cypress. 

See our current workarounds for testing tabs: https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__tab-handling-links

See our workarounds for logging in (which have some logins that would open in new windows). https://github.com/cypress-io/cypress-example-recipes#logging-in-recipes

You'll basically need to stub the function calls and ensure they're being called without opening the new window.

**Comment by Pushpanjali1993** [comment]
Thanks @jennifer-shehane for your quick response. I have tried with above workarounds mentioned, but it didn't resolved my issue. In my above use case, when i click on any button on parent window it generates some events and based on that event new CLI pop-up opens on the child window, which i could not get implemented by using stubs and above all workarounds. Can you please suggest some other way to implement it?

**Comment by jennifer-shehane** [comment]
There is no other way to implement at the moment. You'll need to use stubs and above workarounds for now until we release support for these things.

**Comment by Pushpanjali1993** [comment]
Ok . Thanks for your quick support @jennifer-shehane  will give it a try once again.
