### ISSUE TITLE
Group CI runs

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#49]
How to pass `group` flag via Module API?

https://docs.cypress.io/guides/guides/command-line.html#Cypress-Module-API

https://github.com/cypress-io/cypress-example-recipes/blob/ea547795e8e0b156927d0933dfdcf9ba887107d1/scripts/run.js#L29

**Comment by bahmutov** [comment]
Verified group and groupId against local and staging api. See grouped results at https://dashboard-staging.cypress.io/#/projects/4bmkvy/runs/be5f8e2c-3568-4e3a-845a-a522191c6a08/output

**Comment by bahmutov** [comment]
<img width="949" alt="screen shot 2017-11-30 at 9 29 39 pm" src="https://user-images.githubusercontent.com/2212006/33465393-aa4977d8-d615-11e7-9434-447322e4705d.png">

still not grouped on production

**Comment by jennifer-shehane** [comment]
In the link above I only see that the run timed out:
<img width="1069" alt="screen shot 2017-12-01 at 9 30 49 am" src="https://user-images.githubusercontent.com/1271364/33487239-828114b2-d67a-11e7-9b69-1f4c016f9892.png">
