### ISSUE TITLE
iframe example trouble

### ISSUE THREAD

**Issue by jpeterson** [cypress-io/cypress-example-recipes#502]
Hello, not sure this is the right place for this – feel free to redirect me if appropriate!

I'm new to Cypress and trying to follow the [iframe example here](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/blogs__iframes/cypress/integration/button-spec.js).

My end goal is to write some smoke tests for my app in production, located here: https://aero.esri.com/portal. Unfortunately, the first thing I need to do is login, which is implemented inside an iframe on this page: https://aero.esri.com/portal/home/signin.html.

I'm using the two methods from the example with the only difference being the iframe selector in `getIframeDocument` (there is one and only one iframe on this page).

I'm not sure if Cypress is not finding the iframe, or if I'm using `.find()` improperly once inside the iframe (or something else)?

```js
const getIframeDocument = () => {
  return cy
  .get('iframe')
  // Cypress yields jQuery element, which has the real
  // DOM element under property "0".
  // From the real DOM iframe element we can get
  // the "document" element, it is stored in "contentDocument" property
  // Cypress "its" command can access deep properties using dot notation
  // https://on.cypress.io/its
  // cy.its also waits for the property to exist
  .its('0.contentDocument')
}

const getIframeBody = () => {
  // get the document
  return getIframeDocument()
  // automatically retries until body is loaded
  .its('body').should('not.be.undefined')
  // wraps "body" DOM element to allow
  // chaining more Cypress commands, like ".find(...)"
  // https://on.cypress.io/wrap
  .then(cy.wrap)
}


describe('User can log in', function() {
  it('Loads the sign in page', function() {
    cy.visit('https://aero.esri.com/portal/home/signin.html')
    getIframeBody().find('#ago_Name').click()

	// Enter username
	// Enter password
	// Click sign in button
  })
})

```

My test result:

![image](https://user-images.githubusercontent.com/3399064/83703509-122c6700-a5cd-11ea-8257-b4d79feaca7a.png)

**Comment by jennifer-shehane** [comment]
The example provided is actually working for me. 

It looks like in your example the username field does not display in some situations, like when on smaller screens, so it looks like you've set a viewport height/width that is smaller which collapses these fields. There may be some other situations when these inputs hide, I'm not sure.

So Cypress is not finding the elements because they are not there in the iframe.

<img width="1319" alt="Screen Shot 2020-06-04 at 3 58 21 PM" src="https://user-images.githubusercontent.com/1271364/83740074-63dffa80-a67c-11ea-9134-6d70de94e665.png">

**Comment by jpeterson** [comment]
Thanks for the quick reply @jennifer-shehane!

In my case, I'm not even trying to interact with the username field yet – Cypress is unable to find the "ArcGIS" button `#ago_Name` (which needs to be clicked in order to show the username/password fields), so I don't think I'm running into viewport issues?

One thing I did notice is that when I pin the failed FIND assertion, the DOM Snapshot looks like below, any idea what that means?

![image](https://user-images.githubusercontent.com/3399064/83771855-f2825680-a63f-11ea-9a2c-28bfd62c5d27.png)

**Comment by jennifer-shehane** [comment]
DOM snapshots do not work with iframes https://github.com/cypress-io/cypress/issues/1433 iframes are not completely supported in Cypress https://github.com/cypress-io/cypress/issues/136
