### ISSUE TITLE
Show how to stub window.print

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#522]
- from regular button calling `window.print` in its window
- when the app is using something like https://github.com/gregnb/react-to-print which creates a temporary iframe with its own window

**Comment by callmephilip** [comment]
@bahmutov any luck with `react-to-print`? I've stumbled upon your snippet [here](https://gitter.im/cypress-io/cypress?at=5f063d0eba4e030eeb8ba1fb) but it does not seem to work - the test just hangs

**Comment by bahmutov** [comment]
No, I did not have time to do this unfortunately
