### ISSUE TITLE
Test failing due to cross-origin error

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress-example-recipes#534]
[This test](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/unit-testing__react-apollo/src/App.spec.jsx#L7) is [failing due to a cross-origin error from codesandbox.io](https://app.circleci.com/pipelines/github/cypress-io/cypress-test-example-repos/4383/workflows/fdbc4374-9e0f-4e5c-a636-820d9e17cd2b/jobs/113721/steps). 

![Screen Shot 2020-07-20 at 1 49 23 PM](https://user-images.githubusercontent.com/1157043/87969718-a6289400-ca90-11ea-871b-2be8793d3d54.png)

**Comment by jprealini** [comment]
Just try adding this to your cypress.json

{
  "chromeWebSecurity": false
}

Here's the explanation

https://docs.cypress.io/guides/guides/web-security.html#Disabling-Web-Security
