### ISSUE TITLE
what should i do？The state of the last test case is not available

### ISSUE THREAD

**Issue by SlElegant** [cypress-io/cypress-example-recipes#553]
![image](https://user-images.githubusercontent.com/51369439/91811270-d05d9c00-ec61-11ea-8e9a-9b1bead49020.png)

**Comment by SlElegant** [comment]
![image](https://user-images.githubusercontent.com/51369439/91813811-d05f9b00-ec65-11ea-8ff9-c6323d19a674.png)

**Comment by bahmutov** [comment]
you can use `after` hook to send information about the very last test, see https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/server-communication__stream-tests

**Comment by SlElegant** [comment]
![image](https://user-images.githubusercontent.com/51369439/92679027-ebaf6200-f359-11ea-9758-25ab5653822e.png)

Follow your way，I also use after hook to send information ,but,  The state of the last test case is not available
