### ISSUE TITLE
Setting download path in Chrome using automation does not work on Windows AppVeyor

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#563]
Maybe the slashes?

https://dashboard.cypress.io/projects/6p53jw/runs/37652/specs

https://ci.appveyor.com/project/cypress-io/cypress-example-recipes/builds/35138967

![image](https://user-images.githubusercontent.com/2212006/92792284-66d54000-f37b-11ea-8d77-3a18c8136b46.png)

**Comment by bahmutov** [comment]
To enable remove "no:" from `examples/testing-dom__download/package.json` scripts "no:test:ci:windows" and "no:test:ci:windows:record"

**Comment by pehguerra** [comment]
I am not able to run on my local:

Chrome (Download error):
![image](https://user-images.githubusercontent.com/52336894/104066836-d6035980-51e0-11eb-9547-692aebcfba16.png)

Electron (it's not throwing download error but it's not downloading de file):
![image](https://user-images.githubusercontent.com/52336894/104066924-f7644580-51e0-11eb-9385-feca3bc20a51.png)
