### ISSUE TITLE
Extend the CI job for file download recipe

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#564]
File download recipe https://github.com/cypress-io/cypress-example-recipes#testing-the-dom should be tested on every browser in both headed and in headless modes

**Comment by JamesRLamar** [comment]
Having the same issue. I can get this to pass locally in headless mode, but not in Jenkins/Docker container.

**Comment by bahmutov** [comment]
Even with chrome security set to false?

**Comment by JamesRLamar** [comment]
That is correct. Chrome Web security is false, but the test fails as if the download never began. All other tests locally, whe

**Comment by bahmutov** [comment]
so you can run in Docker container locally and it never triggers the download? What happens when you run this cypress example recipe in a Docker container? I am just thinking how to recreate your problem and how it is different from this recipe

**Comment by JamesRLamar** [comment]
Sorry, locally everything works. Docker, Docker headless, without docker. It's only in Jenkins it fails as if the download never occurred. I'll try to test the sample recipe precisely and see if I can dup, but that' may be a stretch

**Comment by bahmutov** [comment]
done
