### ISSUE TITLE
Add example of data-driven tests

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#62]
Similar to https://github.com/bahmutov/snap-shot-it#data-driven-testing

```js
const names = ['foo', 'bar', 'baz']
names.forEach(name => {
  it(`works for ${name}`, () => {
     cy.visit('...')
     cy.contains(name)
  })
})
```

**Comment by shi745** [comment]
Hi - Do  we have fix available for this ?
I mean do we have recipes- Examples available if we this feature is available ?

**Comment by bahmutov** [comment]
Done in https://github.com/cypress-io/cypress-example-recipes#dynamic-tests

**Comment by Lewiscowles1986** [comment]
if anyone is wondering where this moved it's https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__dynamic-tests
