### ISSUE TITLE
Elevatebart-Thanks for taking the time to open a PR!

### ISSUE THREAD

**Issue by prdarm** [cypress-io/cypress-example-recipes#642]
Thanks for taking the time to open a PR! 

- Create a [Draft Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests) if your PR is not ready for review. [Mark the PR as **Ready for Review**](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request#marking-a-pull-request-as-ready-for-review) when you're ready for a Cypress team member to review the PR.
- Become familiar with the [Code Review Checklist](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#Code-Review-Checklist) for guidelines on coding standards and what needs to be done before a PR can be merged.

_Originally posted by @cypress-bot[bot] in https://github.com/cypress-io/cypress/issues/15136#issuecomment-780966304_

**Comment by prdarm** [comment]
reply+AQWYV3FK36DYW7Q44YOSVBF6HEZ6NEVBNHHBMWMYY4@reply.github.com

**Comment by bahmutov** [comment]
spam
