### ISSUE TITLE
How to keep token login status in multiple test cases？

### ISSUE THREAD

**Issue by guoyupeng01** [cypress-io/cypress-example-recipes#667]
before(() => {
             cy.login_request(LoginUrl, LoginMethod, LoginHeaders, LoginBody) 
        }).its('headers') 
             .then((headers)=>{ 
                  const csrf = headers['x-auth-token'] 
                 cy.log(csrf) 
        }) 
    })
![image](https://user-images.githubusercontent.com/32129782/110564020-236f5900-8187-11eb-994a-dae79e923319.png)

I have obtained the token, but the subsequent UI test cases, how to keep the login status, support to directly open the web page, do not need to log in again

I look forward to your reply

**Comment by bahmutov** [comment]
Please look at our https://github.com/cypress-io/cypress-example-recipes#logging-in-recipes again - if you use `begin` hook it runs once. The second test will have its window and cookies cleared automatically. Thus you need to set the cookie / header again before each test. Something like this

```js
let csrf
before(() => {
  cy.login_request(LoginUrl, LoginMethod, LoginHeaders, LoginBody)
    .its('headers')
    .then((headers)=>{
      csrf = headers['x-auth-token']
    })
})

beforeEach(() => {
  cy.log(csrf)
  // set the csrf or cookie 
})
```
