### ISSUE TITLE
Add TS files to support folder in preprocessor examples

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#67]
To show how Cypress bundles all TS files

**Comment by Konstruktour** [comment]
i faced the following issue:

i renamed  'support/index.js' to 'support/index.ts' & 'support/commands.js' to 'support/commands.ts' in the "preprocessors__typescript-webpack" example and added the line "supportFile":	"cypress/support/index.ts" to cypress.json.
In 'support/commands.ts' i added a new command 'test' and called it in 'integration/spec.ts' through (cy as any).test() (without any import).

this works fine when using "npx cypress open" - but not when using headless mode "npx cypress run"...

error message:

> 
> Oops...we found an error preparing this test file:
> 
>   C:\development\cypress_preprocessor\examples\preprocessors__typescript-webpack\cypress\support\index.ts
> 
> The error was:
> 
> SyntaxError: 'import' and 'export' may only appear at the top level (18:0) while parsing C:\development\cypress_preprocessor\examples\preprocessors__typescript-webpack\cypress\support\index.ts while parsing file: C:\development\cypress_preprocessor\examples\preprocessors__typescript-webpack\cypress\support\index.ts

**Comment by bahmutov** [comment]
hmm, I will need to investigate

**Comment by brian-mann** [comment]
This was a bug in `1.1.4` that's already been fixed and is scheduled for release today.

**Comment by bahmutov** [comment]
In https://github.com/cypress-io/cypress-example-recipes/commit/0677f7a071e534eb5404ca5e801e721a35bb0e91 I am using `support/commands.ts` but not `support/index.ts` - that one is still problematic

**Comment by bahmutov** [comment]
ok, just need to set it in `cypress.json` like you showed @Konstruktour

**Comment by christophechevalier** [comment]
Like this ?
`"include": ["integration/*.ts", "support/*.ts", "../node_modules/cypress"]`

**Comment by bahmutov** [comment]
Yes I think this is correct

**Comment by brian-mann** [comment]
```js
```

**Comment by christophechevalier** [comment]
> ```js
> {
>   "pluginsFile": "cypress/support/index.ts"
> }
> ```

@brian-mann You did mean :
{
  "supportFile": "cypress/support/index.ts"
}

**Comment by andrerpena** [comment]
The support file must be a `.js` file or `.coffee` file:

![image](https://user-images.githubusercontent.com/1581429/73593516-84991780-4505-11ea-8604-f4358baeae52.png)
