### ISSUE TITLE
Show recipe to parse PDF files after download and assert for expected text

### ISSUE THREAD

**Issue by viktorgogulenko** [cypress-io/cypress-example-recipes#678]
I was trying to find a recipe when Cypress downloading a PDF file and parsing it to verify that expected text is in place and found just this one which is really basic and not checking for a expected text as it done for XLSX files - [local-download-spec.js](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__download/cypress/integration/local-download-spec.js#L95)
It would be great to have an example also for PDF-files as well. Thanks in advance!

**Comment by bahmutov** [comment]
Can you suggest a node library for reading a PDF file?

**Comment by viktorgogulenko** [comment]
@bahmutov [pdf-parse](https://www.npmjs.com/package/pdf-parse) seems could be a good candidate. Thanks!
