### ISSUE TITLE
how to verify the text color in cypress

### ISSUE THREAD

**Issue by senthkum** [cypress-io/cypress-example-recipes#718]
Hi Team,

I have a requirement to verify the text color from the application, I googled and tried with multiple code and it did not work, can you please help me with the code.

cy.get('.ico-logout').should('have.css', 'color', '#AF0304')

cy.get('.ico-logout').should('have.css', 'color').and('be.colored', '#AF0304')

![image](https://user-images.githubusercontent.com/46837197/121516614-c14a1c80-ca31-11eb-81c7-5635c3ce4dea.png)

![image](https://user-images.githubusercontent.com/46837197/121516544-ad9eb600-ca31-11eb-9380-ac10287ce624.png)

![image](https://user-images.githubusercontent.com/46837197/121516719-e63e8f80-ca31-11eb-9a5e-d155853181af.png)

Thanks
Senthil. M

**Comment by bahmutov** [comment]
See the recipe https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/extending-cypress__chai-assertions - you need to install additional NPM module with that assertion
