### ISSUE TITLE
Any idea why the offline (server-communication__offline) tests only work when run against localhost?

### ISSUE THREAD

**Issue by Jacob-McKay** [cypress-io/cypress-example-recipes#721]
Using cypress for our project, built wonderful tests of our application with switching to offline and back, deploy the app and run cypress against the hosted url and we get timeouts on the goOffline straight from this example/the blog post (even with an absurd 20s timeout).

Didn't see anything online about network emulation only working for localhost, so I tried the offline recipe here.  Worked great locally, but if I host it somewhere else I get the same result, cypress times out on 'goOffline'.  'goOnline' always seems to work...

Any ideas?  I can send you a link to the site I published if you want, but it's a company server so I didn't want to post that publicly.  I'm wondering if it's something to do with our IT dept managing our chrome instance?  Seems like a longshot

**Comment by raultm** [comment]
Did you find any solution?

In localhost online/offline switch goes smoothly, but in my case after going offline it doesnt become online again when not on localhost

**Comment by svenjungnickel** [comment]
I am having the same issues. The funny part is, it worked seamlessly in older version of cypress, not only on localhost. But since version 7 I have the same timeout issues. 
I studied the migration guide and found this part: https://docs.cypress.io/guides/references/migration-guide#Uncaught-exception-and-unhandled-rejections. I thought it might be reason for the issues but the solution did not help.

I hope that might help.

**Comment by raultm** [comment]
Make sense, i found https://github.com/cypress-io/cypress/issues/17723#issuecomment-906152925 this comment where 
szhong-becls says that the problem could be rippled from a change in a dependency, and the websocket is closed if offline mode and server is no localhost.

What version of cypress do you use in retropective to make the tests works?

6.XX.YY?

**Comment by svenjungnickel** [comment]
I had it working in version 6.3.0 and I also tested it also successfully in version 6.9.1.

**Comment by Jacob-McKay** [comment]
I'm using the following workaround until a fix lands.  It works for me because the app I'm working on is a SPA that checks navigator.onLine before it tries to do anything network related:

```
export const goOffline = () => {
    cy.log('**go offline**')
        .then(() => cy.window({ log: false }))
        .then((winder: any) => {
            winder.originalNavigator = winder.navigator;

            let jankNavigator = Object.create(winder.navigator);
            Object.defineProperty(jankNavigator, 'onLine', {
                get() { return false; }
            });

            Object.defineProperty(winder, 'navigator', {
                get() { return jankNavigator }
            });
        });
}

export const goOnline = () => {
    cy.log('**go online**')
        .then(() => cy.window({ log: false }))
        .then((winder: any) => {
            if (winder.originalNavigator === undefined) {
                return;
            }
            Object.defineProperty(winder, 'navigator', {
                get() { return winder.originalNavigator }
            });
        });
}

```

There is also this suggested workaround that I have not tried: https://github.com/cypress-io/cypress/issues/235#issuecomment-878421750

**Comment by lorenzofidalgo** [comment]
> I am having the same issues. The funny part is, it worked seamlessly in older version of cypress, not only on localhost. But since version 7 I have the same timeout issues. I studied the migration guide and found this part: https://docs.cypress.io/guides/references/migration-guide#Uncaught-exception-and-unhandled-rejections. I thought it might be reason for the issues but the solution did not help.
> 
> I hope that might help.

I have just reproduced this issue with Cypress 8.4.0 and Chrome 96. NEVERTHELESS, it is able to go online again against Electron 91 but not against Chrome 96.
The code I use to go online again includes the following:

```
Cypress.automation('remote:debugger:protocol',
      {
        command: 'Network.emulateNetworkConditions',
        params: {
          **offline: false,**
          latency: -1,
          downloadThroughput: -1,
          uploadThroughput: -1,
        },
      })
```

**Comment by lorenzofidalgo** [comment]
After some more testing, I have confirmed Cypress 6.9.1 is still working properly.
I have tested Cypress 6.9.1 against Chrome 96 and Electron 87 (working properly in both cases).
