### ISSUE TITLE
Can you clarify your example for "Environment variables"

### ISSUE THREAD

**Issue by djangofan** [cypress-io/cypress-example-recipes#738]
Can you clarify your example for "Environment variables"

The documentation does not answer this question: https://docs.cypress.io/guides/guides/environment-variables#Option-1-configuration-file

It appears you are suggesting that I hard-code the env-name in my code ( https://github.com/cypress-io/cypress-example-recipes/blob/2e5fb3da420f544637ff77d81ff7261f5d2164e8/examples/server-communication__env-variables/cypress/integration/spec.js#L5 ).   I cannot do that.  Can you clarify how I could pass the environment name to the Cypress tests, on the command line at execution time, to load a group of variables?   Your example makes no attempt to answer that question.

**Comment by bahmutov** [comment]
You cannot hardcore the environment variable name? How does your test then know what to access? Can you give pseudocode for what you are trying to do or want to achieve

**Comment by djangofan** [comment]
I was able to find the document that clarified it,  which provides some sample code.   It worked for me.   Problem was that this document was not easy to find , since I was assuming that the previously mentioned link was the only document on this.

So, the solution was found here:
https://docs.cypress.io/api/plugins/configuration-api#Switch-between-multiple-configuration-files

Would be nice to bake that into an example don't you think?
