### ISSUE TITLE
Whether the ID of iframe can be located in cypress

### ISSUE THREAD

**Issue by luqy** [cypress-io/cypress-example-recipes#798]
I tried to use the ID to locate, but I was prompted that I could not find it

![image](https://user-images.githubusercontent.com/42463694/194698248-c7647913-4994-4e8c-a82b-79fae9c9c43f.png)

![image](https://user-images.githubusercontent.com/42463694/194698225-ae0f007b-d74d-44b4-90a7-9712dba5fe61.png)

**Comment by Arghajit47ldp** [comment]
![image](https://github.com/cypress-io/cypress-example-recipes/assets/102297947/6c7267ea-9dc2-47e0-9b45-a0338208689c)
For me in the webpage, there isn't any id locator is available.
If there is any then I guess we can use that as well as a locator
For your reference, you can refer to this below sreenshots:
![image](https://github.com/cypress-io/cypress-example-recipes/assets/102297947/4b65cf18-906c-478a-a420-6010580676cc)
