### ISSUE TITLE
Add recipe testing A11Y

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#80]
use one of these libraries to check element / page

• https://github.com/pa11y/pa11y 
• https://github.com/paypal/AATT 
• http://bit.ly/gha11yjs 
• http://bit.ly/axetool 
• http://colorsafe.co 
• http://jxnblk.com/colorable/ 
• https://sonarwhal.com/ 
• http://bit.ly/a11ycss 
• http://www.funkify.org 

For this https://twitter.com/khaled_garbaya/status/943859388841938944

**Comment by Khaledgarbaya** [comment]
There is also https://github.com/addyosmani/a11y which looks great.
As an example website maybe we can use this https://github.com/aduggin/accessibility-fails

**Comment by marcysutton** [comment]
You could use [axe-core](https://github.com/dequelabs/axe-core) for this (the accessibility library powering sonarwhal and Lighthouse, the successor to a11y). You have to inject the script into a page and then you can run the aXe API on it.

**Comment by avanslaars** [comment]
[cypress-axe](https://github.com/avanslaars/cypress-axe) does exactly what @marcysutton suggested above.

**Comment by bahmutov** [comment]
https://twitter.com/stefanjudis/status/1108032172852760576
