### ISSUE TITLE
can you make sample for combination e2e insteade of separate cases

### ISSUE THREAD

**Issue by yogithesymbian** [cypress-io/cypress-example-recipes#829]
its good to combination ? then which one the best for doing like that ? for saving bearer maybe and other payload option if there is one more payload then can be interact to other test in one job . or we must make it seperate cases ? 
i think when we are going to test , need to capture UI thats mean needed load api thats mean combination . i can do that by i doubt my implementation is not good , hope u make it and clear .

**Comment by jennifer-shehane** [comment]
E2E and CT tests have to run separately due to the differences in setup that needs to run and in order to not break the way people's old E2E tests run unfortunately.
