### ISSUE TITLE
Test spy retries

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#86]
Seems spy via alias does not retry waiting for the function to be called.

**Comment by bahmutov** [comment]
<img width="449" alt="screen shot 2018-01-05 at 1 41 12 pm" src="https://user-images.githubusercontent.com/2212006/34623214-48af6814-f21e-11e7-8b41-df4db6f34e16.png">

**Comment by brian-mann** [comment]
Fixed in https://github.com/cypress-io/cypress/pull/1294
